pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git url: 'git@github.com:whz1gud/SeleniumTesting.git', credentialsId: 'github-ssh-key'
      }
    }
    stage('Restore') {
      steps {
        sh 'dotnet restore Task3/Task3.csproj'
      }
    }
    stage('Build') {
      steps {
        sh 'dotnet build Task3/Task3.csproj --configuration Release'
      }
    }
    stage('Test') {
      steps {
        sh 'dotnet test Task3/Task3.csproj --configuration Release --no-build'
      }
    }
  }
  post {
    always {
      junit '**/TestResults/*.xml'
    }
  }
}
