pipeline {
  agent any
  stages {
    stage('Restore') {
      steps {
        sh 'dotnet restore Task3/Task3.csproj'
      }
    }
    stage('Build') {
      steps {
        sh 'dotnet build Task3/Task3.csproj --configuration Release'
      }
    }
    stage('Test') {
      steps {
        sh 'dotnet test Task3/Task3.csproj --configuration Release --no-build --logger "nunit;LogFileName=TestResults/TestResults.xml"'
      }
    }
  }
  post {
    always {
      nunit testResultsPattern: 'Task3/TestResults/TestResults.xml'
    }
  }
}
